/*
 * errcodes.h
 *
 *  Created on: 20.09.2016
 *      Author: elenz
 */

#ifndef ERRCODES_H_
#define ERRCODES_H_

//#include <stdint.h>

#define ERRCODE_GRPFLAG_COMM	0x0100
#define ERRCODE_GRPFLAG_MISC	0x0200
#define ERRCODE_GRPFLAG_DAQ		0x0400

typedef enum EnErrCode_
{
	ERRCODE_NOERR = 0,
	ERRCODE_UNKNOWNERROR = 1,
	ERRCODE_COMM_UNEXPECT = ERRCODE_GRPFLAG_COMM | 0,
	ERRCODE_COMM_SECONDARYUART = ERRCODE_GRPFLAG_COMM | 1,
	ERRCODE_COMM_WRONGSOT = ERRCODE_GRPFLAG_COMM | 2,
	ERRCODE_COMM_MSGTOOLONG = ERRCODE_GRPFLAG_COMM | 3,
	ERRCODE_COMM_OVERRUN = ERRCODE_GRPFLAG_COMM | 4,
	ERRCODE_COMM_WRONGUSAGE = ERRCODE_GRPFLAG_COMM | 5,
	ERRCODE_COMM_READONLY = ERRCODE_GRPFLAG_COMM | 6,
	ERRCODE_COMM_WRITEONLY = ERRCODE_GRPFLAG_COMM | 7,
	ERRCODE_COMM_UNKNOWNCMD = ERRCODE_GRPFLAG_COMM | 8,
	ERRCODE_COMM_INVALIDCMDTABLE = ERRCODE_GRPFLAG_COMM | 9,
	ERRCODE_COMM_VALUEOUTOFRANGE = ERRCODE_GRPFLAG_COMM | 10,
	ERRCODE_COMM_NOTYETIMPLEMENTED = ERRCODE_GRPFLAG_COMM | 11,
	ERRCODE_COMM_PARSEERROR = ERRCODE_GRPFLAG_COMM | 12,
	ERRCODE_COMM_MSGCORRUPTED = ERRCODE_GRPFLAG_COMM | 13,
	ERRCODE_DISPLAY_MSGDROPPED = ERRCODE_GRPFLAG_MISC | 1,
	ERRCODE_DAQ_INVALIDPARAMETER = ERRCODE_GRPFLAG_DAQ | 1,
	ERRCODE_DAQ_CONTRADICTINGPARAMETERS = ERRCODE_GRPFLAG_DAQ | 2,
	ERRCODE_DAQ_INVALIDCHANNEL = ERRCODE_GRPFLAG_DAQ | 3,
	ERRCODE_DAQ_UNKNOWNPARAMETER = ERRCODE_GRPFLAG_DAQ | 4,
	ERRCODE_DAQ_MSGDROPPED = ERRCODE_GRPFLAG_DAQ | 5,
	ERRCODE_DAQ_INVALIDPACKAGE = ERRCODE_GRPFLAG_DAQ | 6,
	ERRCODE_DAQ_UNKNOWNPACKAGE = ERRCODE_GRPFLAG_DAQ | 7,
} EnErrCode_t;


#endif /* ERRCODES_H_ */
