/*
 * errcodes.h
 *
 *  Created on: 20.09.2016
 *      Author: elenz
 */

#ifndef ERRCODES_H_
#define ERRCODES_H_

//#include <stdint.h>

#define ERRCODE_GRPFLAG_COMM	0x0100

typedef enum EnErrCode_
{
	ERRCODE_NOERR = 0,
	ERRCODE_UNKNOWNERROR = 1,
	ERRCODE_COMM_UNEXPECT = ERRCODE_GRPFLAG_COMM | 0,
	ERRCODE_COMM_SECONDARYUART = ERRCODE_GRPFLAG_COMM | 1,
	ERRCODE_COMM_WRONGSOT = ERRCODE_GRPFLAG_COMM | 2,
	ERRCODE_COMM_MSGTOOLONG = ERRCODE_GRPFLAG_COMM | 3,
	ERRCODE_COMM_OVERRUN = ERRCODE_GRPFLAG_COMM | 4,
	ERRCODE_COMM_WRONGUSAGE = ERRCODE_GRPFLAG_COMM | 5,
} EnErrCode_t;


#endif /* ERRCODES_H_ */
