/*
 * mpu9250_privatedefs.h
 *
 *  Created on: 16.09.2016
 *      Author: elenz
 */

#ifndef IMU_MPU9250_PRIVATEDEFS_H_
#define IMU_MPU9250_PRIVATEDEFS_H_


#define READFLAG    (1 << 7)
#define WRITEFLAG    (0 << 7)

#define READCMD(reg) ( READFLAG | (reg) )
#define WRITECMD(reg) ( WRITEFLAG | (reg) )


typedef enum EnRegister_
{
    REG_SELF_TEST_X_GYRO = 0x00,
    REG_SELF_TEST_Y_GYRO = 0x01,
    REG_SELF_TEST_Z_GYRO = 0x02,
    REG_SELF_TEST_X_ACCEL = 0x0D,
    REG_SELF_TEST_Y_ACCEL = 0x0E,
    REG_SELF_TEST_Z_ACCEL = 0x0F,
    REG_XG_OFFSET_H = 0x13,
    REG_XG_OFFSET_L = 0x14,
    REG_YG_OFFSET_H = 0x15,
    REG_YG_OFFSET_L = 0x16,
    REG_ZG_OFFSET_H = 0x17,
    REG_ZG_OFFSET_L = 0x18,
    REG_SMPLRT_DIV = 0x19,
    REG_CONFIG = 0x1A,
    REG_GYRO_CONFIG = 0x1B,
    REG_ACCEL_CONFIG = 0x1C,
    REG_ACCEL_CONFIG2 = 0x1D,
    REG_LP_ACCEL_ODR = 0x1E,
    REG_WOM_THR = 0x1F,
    REG_FIFO_EN = 0x23,
    REG_I2C_MST_CTRL = 0x24,
    REG_I2C_SLV0_ADDR = 0x25,
    REG_I2C_SLV0_REG = 0x26,
    REG_I2C_SLV0_CTRL = 0x27,
    REG_I2C_SLV1_ADDR = 0x28,
    REG_I2C_SLV1_REG = 0x29,
    REG_I2C_SLV1_CTRL = 0x2A,
    REG_I2C_SLV2_ADDR = 0x2B,
    REG_I2C_SLV2_REG = 0x2C,
    REG_I2C_SLV2_CTRL = 0x2D,
    REG_I2C_SLV3_ADDR = 0x2E,
    REG_I2C_SLV3_REG = 0x2F,
    REG_I2C_SLV3_CTRL = 0x30,
    REG_I2C_SLV4_ADDR = 0x31,
    REG_I2C_SLV4_REG = 0x32,
    REG_I2C_SLV4_DO = 0x33,
    REG_I2C_SLV4_CTRL = 0x34,
    REG_I2C_SLV4_DI = 0x35,
    REG_I2C_MST_STATUS = 0x36,
    REG_INT_PIN_CFG = 0x37,
    REG_INT_ENABLE = 0x38,
    REG_INT_STATUS = 0x3A,
    REG_ACCEL_XOUT_H = 0x3B,
    REG_ACCEL_XOUT_L = 0x3C,
    REG_ACCEL_YOUT_H = 0x3D,
    REG_ACCEL_YOUT_L = 0x3E,
    REG_ACCEL_ZOUT_H = 0x3F,
    REG_ACCEL_ZOUT_L = 0x40,
    REG_TEMP_OUT_H = 0x41,
    REG_TEMP_OUT_L = 0x42,
    REG_GYRO_XOUT_H = 0x43,
    REG_GYRO_XOUT_L = 0x44,
    REG_GYRO_YOUT_H = 0x45,
    REG_GYRO_YOUT_L = 0x46,
    REG_GYRO_ZOUT_H = 0x47,
    REG_GYRO_ZOUT_L = 0x48,
    REG_EXT_SENS_DATA_00 = 0x49,
    REG_EXT_SENS_DATA_01 = 0x4A,
    REG_EXT_SENS_DATA_02 = 0x4B,
    REG_EXT_SENS_DATA_03 = 0x4C,
    REG_EXT_SENS_DATA_04 = 0x4D,
    REG_EXT_SENS_DATA_05 = 0x4E,
    REG_EXT_SENS_DATA_06 = 0x4F,
    REG_EXT_SENS_DATA_07 = 0x50,
    REG_EXT_SENS_DATA_08 = 0x51,
    REG_EXT_SENS_DATA_09 = 0x52,
    REG_EXT_SENS_DATA_10 = 0x53,
    REG_EXT_SENS_DATA_11 = 0x54,
    REG_EXT_SENS_DATA_12 = 0x55,
    REG_EXT_SENS_DATA_13 = 0x56,
    REG_EXT_SENS_DATA_14 = 0x57,
    REG_EXT_SENS_DATA_15 = 0x58,
    REG_EXT_SENS_DATA_16 = 0x59,
    REG_EXT_SENS_DATA_17 = 0x5A,
    REG_EXT_SENS_DATA_18 = 0x5B,
    REG_EXT_SENS_DATA_19 = 0x5C,
    REG_EXT_SENS_DATA_20 = 0x5D,
    REG_EXT_SENS_DATA_21 = 0x5E,
    REG_EXT_SENS_DATA_22 = 0x5F,
    REG_EXT_SENS_DATA_23 = 0x60,
    REG_I2C_SLV0_DO = 0x63,
    REG_I2C_SLV1_DO = 0x64,
    REG_I2C_SLV2_DO = 0x65,
    REG_I2C_SLV3_DO = 0x66,
    REG_I2C_MST_DELAY_CTRL = 0x67,
    REG_SIGNAL_PATH_RESET = 0x68,
    REG_MOT_DETECT_CTRL = 0x69,
    REG_USER_CTRL = 0x6A,
    REG_PWR_MGMT_1 = 0x6B,
    REG_PWR_MGMT_2 = 0x6C,
    REG_FIFO_COUNTH = 0x72,
    REG_FIFO_COUNTL = 0x73,
    REG_FIFO_R_W = 0x74,
    REG_WHO_AM_I = 0x75,
    REG_XA_OFFSET_H = 0x77,
    REG_XA_OFFSET_L = 0x78,
    REG_YA_OFFSET_H = 0x7A,
    REG_YA_OFFSET_L = 0x7B,
    REG_ZA_OFFSET_H = 0x7D,
    REG_ZA_OFFSET_L = 0x7E,
} EnRegister_t;


#define WHO_AM_I_VALUE    0x71


// CONFIG
#define CONFIG_FIFOMODE_MASK        (1 << 6)
#define CONFIG_FIFOMODE_DISCARD        (1 << 6)
#define CONFIG_FIFOMODE_OVERWRITE    (0 << 6)

#define CONFIG_EXTSYNCSET_MASK            (7 << 3)
#define CONFIG_EXTSYNCSET_DISABLED        (0 << 3)
#define CONFIG_EXTSYNCSET_TEMPOUTL        (1 << 3)
#define CONFIG_EXTSYNCSET_GYROXOUTL        (2 << 3)
#define CONFIG_EXTSYNCSET_GYROYOUTL        (3 << 3)
#define CONFIG_EXTSYNCSET_GYROZOUTL        (4 << 3)
#define CONFIG_EXTSYNCSET_ACCELXOUTL    (5 << 3)
#define CONFIG_EXTSYNCSET_ACCELYOUTL    (6 << 3)
#define CONFIG_EXTSYNCSET_ACCELZOUTL    (7 << 3)

#define CONFIG_DLPFCFG_MASK                (3 << 0)
#define CONFIG_DLPFCFG_GYROBW8800_FS32k    (0 << 0)
#define CONFIG_DLPFCFG_GYROBW3600_FS32k    (0 << 0)
#define CONFIG_DLPFCFG_GYROBW250_FS8k    (0 << 0)
#define CONFIG_DLPFCFG_GYROBW184_FS1k    (1 << 0)
#define CONFIG_DLPFCFG_GYROBW92_FS1k    (2 << 0)
#define CONFIG_DLPFCFG_GYROBW41_FS1k    (3 << 0)
#define CONFIG_DLPFCFG_GYROBW20_FS1k    (4 << 0)
#define CONFIG_DLPFCFG_GYROBW10_FS1k    (5 << 0)
#define CONFIG_DLPFCFG_GYROBW5_FS1k        (6 << 0)
#define CONFIG_DLPFCFG_GYROBW3600_FS8k    (7 << 0)


// GYRO_CONFIG
#define GYROCONFIG_SELFTEST_MASK

#define GYROCONFIG_FULLSCALESEL_MASK    (3 << 3)
#define GYROCONFIG_FULLSCALESEL_250        (0 << 3)
#define GYROCONFIG_FULLSCALESEL_500        (1 << 3)
#define GYROCONFIG_FULLSCALESEL_1000    (2 << 3)
#define GYROCONFIG_FULLSCALESEL_2000    (3 << 3)

#define GYROCONFIG_FCHOICEB_MASK                (3 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW8800_FS32k    (3 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW3600_FS32k    (2 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW250_FS8k        (0 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW184_FS1k        (0 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW92_FS1k        (0 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW41_FS1k        (0 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW20_FS1k        (0 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW10_FS1k        (0 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW5_FS1k        (0 << 0)
#define GYROCONFIG_FCHOICEB_GYROBW3600_FS8k        (0 << 0)


// ACCEL_CONFIG
#define ACCELCONFIG_SELFTEST_MASK

#define ACCELCONFIG_FULLSCALESEL_MASK    (3 << 3)
#define ACCELCONFIG_FULLSCALESEL_2        (0 << 3)
#define ACCELCONFIG_FULLSCALESEL_4        (1 << 3)
#define ACCELCONFIG_FULLSCALESEL_8        (2 << 3)
#define ACCELCONFIG_FULLSCALESEL_16        (3 << 3)

// ACCEL_CONFIG2
#define ACCELCONFIG2_FCHOICEB_MASK            (1 << 3)
#define ACCELCONFIG2_FCHOICEB_BW1046_FS4k    (1 << 3)
#define ACCELCONFIG2_FCHOICEB_BW218_FS1k    (0 << 3)
#define ACCELCONFIG2_FCHOICEB_BW218__FS1k    (0 << 3)
#define ACCELCONFIG2_FCHOICEB_BW99_FS1k        (0 << 3)
#define ACCELCONFIG2_FCHOICEB_BW45_FS1k        (0 << 3)
#define ACCELCONFIG2_FCHOICEB_BW21_FS1k        (0 << 3)
#define ACCELCONFIG2_FCHOICEB_BW10_FS1k        (0 << 3)
#define ACCELCONFIG2_FCHOICEB_BW5_FS1k        (0 << 3)
#define ACCELCONFIG2_FCHOICEB_BW420_FS1k    (0 << 3)

#define ACCELCONFIG2_DLPFCFG_MASK            (3 << 0)
#define ACCELCONFIG2_DLPFCFG_BW1046_FS4k    (0 << 0)
#define ACCELCONFIG2_DLPFCFG_BW218_FS1k        (0 << 0)
#define ACCELCONFIG2_DLPFCFG_BW218__FS1k    (1 << 0)
#define ACCELCONFIG2_DLPFCFG_BW99_FS1k        (2 << 0)
#define ACCELCONFIG2_DLPFCFG_BW45_FS1k        (3 << 0)
#define ACCELCONFIG2_DLPFCFG_BW21_FS1k        (4 << 0)
#define ACCELCONFIG2_DLPFCFG_BW10_FS1k        (5 << 0)
#define ACCELCONFIG2_DLPFCFG_BW5_FS1k        (6 << 0)
#define ACCELCONFIG2_DLPFCFG_BW420_FS1k        (7 << 0)



// USERCTRL
#define USERCTRL_FIFOEN_MASK        (1 << 6)
#define USERCTRL_FIFOEN_ENABLEFIFO    (1 << 6)
#define USERCTRL_FIFOEN_DISABLEFIFO    (0 << 6)

#define USERCTRL_I2CMSTEN_MASK            (1 << 5)
#define USERCTRL_I2CMSTEN_ENABLEI2CMST    (1 << 5)
#define USERCTRL_I2CMSTEN_DISABLEI2CMST    (0 << 5)

#define USERCTRL_I2CIFDIS_MASK            (1 << 4)
#define USERCTRL_I2CIFDIS_DISABLEI2CSLV    (1 << 4)
#define USERCTRL_I2CIFDIS_ENABLEI2CSLV    (0 << 4)

#define USERCTRL_FIFORST_MASK        (1 << 2)
#define USERCTRL_FIFORST_RESET        (1 << 2)

#define USERCTRL_I2CMSTRST_MASK        (1 << 1)
#define USERCTRL_I2CMSTRST_RESET    (1 << 1)

#define USERCTRL_SIGCONDRST_MASK    (1 << 0)
#define USERCTRL_SIGCONDRST_RESET    (1 << 0)


// I2CSLVXADDR
#define I2CSLVXADDR_RWFLAG_READ        (1 << 7)
#define I2CSLVXADDR_RWFLAG_WRITE    (0 << 7)

// I2CSLVXCTRL
#define I2CSLVXCTRL_EN                (1 << 7)
#define I2CSLVXCTRL_SWAPBYTES        (1 << 6)
#define I2CSLVXCTRL_REGDIS            (1 << 5)
#define I2CSLVXCTRL_GRP_START0        (0 << 4)
#define I2CSLVXCTRL_GRP_START1        (1 << 4)
#define I2CSLVXCTRL_LENGTH_MASK        (15 << 0)



#endif /* IMU_MPU9250_PRIVATEDEFS_H_ */
