/*
 * led.h
 *
 *  Created on: 29.09.2016
 *      Author: elenz
 */


#include "stdtypes.h"


void LED_loopForever_showErrCode(uint8_t uErrCode);


#define LEDERRCODE_STDEXCEPTION        0x80

#define LEDERRCODE_ASSERTFAILED        LEDERRCODE_STDEXCEPTION | 1
#define LEDERRCODE_NMI                LEDERRCODE_STDEXCEPTION | 2
#define LEDERRCODE_HARDFAULT        LEDERRCODE_STDEXCEPTION | 3
#define LEDERRCODE_MEMMANAGE        LEDERRCODE_STDEXCEPTION | 4
#define LEDERRCODE_BUSFAULT            LEDERRCODE_STDEXCEPTION | 5
#define LEDERRCODE_USAGEFAULT        LEDERRCODE_STDEXCEPTION | 6
#define LEDERRCODE_DEBUGMON            LEDERRCODE_STDEXCEPTION | 7
#define LEDERRCODE_SVC                LEDERRCODE_STDEXCEPTION | 8
#define LEDERRCODE_PENDSV            LEDERRCODE_STDEXCEPTION | 9


